### ISSUE TITLE
大佬 我对这个也非常感兴趣 可否一起交流交流

### ISSUE THREAD

**Issue by A2Data** [luoyeah/wechat-frida#1]
还有类似的 项目，是否可以增加完善呢，只懂部分python
https://github.com/chengciming/wechatPc/blob/master/WechatDll/WechatDll/WechatOffset.h

**Comment by luoyeah** [comment]
该项目只实现了最基本功能，仅供学习交流，欢迎提交代码。

**Comment by A2Data** [comment]
可以完善，但是不太懂js 那些操作呀，可以写调用 hh

**Comment by luoyeah** [comment]
可以加qq交流，1403287193

**Comment by A2Data** [comment]
好的 加了， 我的Wx ： F868720
