### ISSUE TITLE
Why not x64 version of WeChatWin.dll

### ISSUE THREAD

**Issue by y0umu** [luoyeah/wechat-frida#2]
Hi developer. You mentioned in README.md that the repo supports some wechat version 3.9 but x86 only. I am curious why there are so many wechat injectors but one can hardly find x64 ones.

As a side note, I attempted to locate the sendmessage call in wechatwin.dll (x64) myself. I tried to search the machine code of `push 0x01`, `add esp,0x18` or `add rsp,0x18` but cannot find any possible call similar to what is described in https://github.com/luoyeah/wechat-frida/blob/main/wechatf/js/v3_9_5_80/send_message.md

**Comment by luoyeah** [comment]
这需要逆向分析 3.9版本 x64位的wechatwin.dll，然后编写特定的send_message.js文件，当前只适配了32位的dll。欢迎编写适配代码然后。
